# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training_form.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.block_1 = QtWidgets.QWidget(self.centralwidget)
        self.block_1.setGeometry(QtCore.QRect(0, 0, 960, 540))
        self.block_1.setMinimumSize(QtCore.QSize(960, 540))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_1.setFont(font)
        self.block_1.setAutoFillBackground(False)
        self.block_1.setStyleSheet("border: 1px solid rgb(0, 0, 0); background: #f3f3f4")
        self.block_1.setObjectName("block_1")
        self.label = QtWidgets.QLabel(self.block_1)
        self.label.setGeometry(QtCore.QRect(0, 0, 961, 541))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.block_2 = QtWidgets.QWidget(self.centralwidget)
        self.block_2.setGeometry(QtCore.QRect(960, 0, 960, 540))
        self.block_2.setMinimumSize(QtCore.QSize(960, 540))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_2.setFont(font)
        self.block_2.setAutoFillBackground(False)
        self.block_2.setStyleSheet("border: 1px solid rgb(0, 0, 0); background: #f3f3f4")
        self.block_2.setObjectName("block_2")
        self.label_2 = QtWidgets.QLabel(self.block_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 961, 541))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.block_4 = QtWidgets.QWidget(self.centralwidget)
        self.block_4.setGeometry(QtCore.QRect(0, 540, 960, 540))
        self.block_4.setMinimumSize(QtCore.QSize(960, 540))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_4.setFont(font)
        self.block_4.setAutoFillBackground(False)
        self.block_4.setStyleSheet("border: 1px solid rgb(0, 0, 0); background: #f3f3f4")
        self.block_4.setObjectName("block_4")
        self.label_4 = QtWidgets.QLabel(self.block_4)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 961, 541))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.block_3 = QtWidgets.QWidget(self.centralwidget)
        self.block_3.setGeometry(QtCore.QRect(960, 540, 960, 540))
        self.block_3.setMinimumSize(QtCore.QSize(960, 540))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_3.setFont(font)
        self.block_3.setAutoFillBackground(False)
        self.block_3.setStyleSheet("border: 1px solid rgb(0, 0, 0); background: #f3f3f4")
        self.block_3.setObjectName("block_3")
        self.label_3 = QtWidgets.QLabel(self.block_3)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 961, 541))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "2"))
        self.label_4.setText(_translate("MainWindow", "3"))
        self.label_3.setText(_translate("MainWindow", "4"))

