# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training_form.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.block_1 = QtWidgets.QWidget(self.centralwidget)
        self.block_1.setGeometry(QtCore.QRect(0, 0, 267, 201))
        self.block_1.setMinimumSize(QtCore.QSize(267, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_1.setFont(font)
        self.block_1.setAutoFillBackground(False)
        self.block_1.setStyleSheet("border: 1px solid rgb(0, 0, 0); background:rgb(244, 254, 255)")
        self.block_1.setObjectName("block_1")
        self.label = QtWidgets.QLabel(self.block_1)
        self.label.setGeometry(QtCore.QRect(0, 0, 271, 201))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.block_2 = QtWidgets.QWidget(self.centralwidget)
        self.block_2.setGeometry(QtCore.QRect(268, 0, 266, 200))
        self.block_2.setMinimumSize(QtCore.QSize(266, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_2.setFont(font)
        self.block_2.setAutoFillBackground(False)
        self.block_2.setStyleSheet("border: 1px solid rgb(0, 0, 0); background:rgb(244, 254, 255)")
        self.block_2.setObjectName("block_2")
        self.label_2 = QtWidgets.QLabel(self.block_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 266, 201))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.block_3 = QtWidgets.QWidget(self.centralwidget)
        self.block_3.setGeometry(QtCore.QRect(532, 0, 266, 200))
        self.block_3.setMinimumSize(QtCore.QSize(266, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_3.setFont(font)
        self.block_3.setAutoFillBackground(False)
        self.block_3.setStyleSheet("border: 1px solid rgb(0, 0, 0); background:rgb(244, 254, 255)")
        self.block_3.setObjectName("block_3")
        self.label_5 = QtWidgets.QLabel(self.block_3)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 266, 201))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.block_5 = QtWidgets.QWidget(self.centralwidget)
        self.block_5.setGeometry(QtCore.QRect(268, 200, 266, 200))
        self.block_5.setMinimumSize(QtCore.QSize(266, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_5.setFont(font)
        self.block_5.setAutoFillBackground(False)
        self.block_5.setStyleSheet("border: 1px solid rgb(0, 0, 0); background:rgb(244, 254, 255)")
        self.block_5.setObjectName("block_5")
        self.label_8 = QtWidgets.QLabel(self.block_5)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 266, 201))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.block_6 = QtWidgets.QWidget(self.centralwidget)
        self.block_6.setGeometry(QtCore.QRect(532, 200, 266, 200))
        self.block_6.setMinimumSize(QtCore.QSize(266, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_6.setFont(font)
        self.block_6.setAutoFillBackground(False)
        self.block_6.setStyleSheet("border: 1px solid rgb(0, 0, 0); background:rgb(244, 254, 255)")
        self.block_6.setObjectName("block_6")
        self.label_7 = QtWidgets.QLabel(self.block_6)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 266, 201))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.block_4 = QtWidgets.QWidget(self.centralwidget)
        self.block_4.setGeometry(QtCore.QRect(0, 200, 269, 200))
        self.block_4.setMinimumSize(QtCore.QSize(266, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_4.setFont(font)
        self.block_4.setAutoFillBackground(False)
        self.block_4.setStyleSheet("border: 1px solid rgb(0, 0, 0); background:rgb(244, 254, 255)")
        self.block_4.setObjectName("block_4")
        self.label_6 = QtWidgets.QLabel(self.block_4)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 269, 201))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.block_9 = QtWidgets.QWidget(self.centralwidget)
        self.block_9.setGeometry(QtCore.QRect(532, 400, 266, 200))
        self.block_9.setMinimumSize(QtCore.QSize(266, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_9.setFont(font)
        self.block_9.setAutoFillBackground(False)
        self.block_9.setStyleSheet("border: 1px solid rgb(0, 0, 0); background:rgb(244, 254, 255)")
        self.block_9.setObjectName("block_9")
        self.label_9 = QtWidgets.QLabel(self.block_9)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 266, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.block_7 = QtWidgets.QWidget(self.centralwidget)
        self.block_7.setGeometry(QtCore.QRect(1, 400, 269, 200))
        self.block_7.setMinimumSize(QtCore.QSize(266, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_7.setFont(font)
        self.block_7.setAutoFillBackground(False)
        self.block_7.setStyleSheet("border: 1px solid rgb(0, 0, 0); background:rgb(244, 254, 255)")
        self.block_7.setObjectName("block_7")
        self.label_10 = QtWidgets.QLabel(self.block_7)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 269, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.block_8 = QtWidgets.QWidget(self.centralwidget)
        self.block_8.setGeometry(QtCore.QRect(268, 400, 265, 200))
        self.block_8.setMinimumSize(QtCore.QSize(265, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.block_8.setFont(font)
        self.block_8.setAutoFillBackground(False)
        self.block_8.setStyleSheet("border: 1px solid rgb(0, 0, 0); background:rgb(244, 254, 255)")
        self.block_8.setObjectName("block_8")
        self.label_11 = QtWidgets.QLabel(self.block_8)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 265, 200))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.block_1.raise_()
        self.block_2.raise_()
        self.block_3.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.block_5.raise_()
        self.block_6.raise_()
        self.block_4.raise_()
        self.block_9.raise_()
        self.block_7.raise_()
        self.block_8.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "3"))
        self.label_8.setText(_translate("MainWindow", "5"))
        self.label_7.setText(_translate("MainWindow", "6"))
        self.label_6.setText(_translate("MainWindow", "4"))
        self.label_9.setText(_translate("MainWindow", "9"))
        self.label_10.setText(_translate("MainWindow", "7"))
        self.label_11.setText(_translate("MainWindow", "8"))

